# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Chi Po Choi
tagline:          'Po'
description:      'PhD student in Statistics at UC Davis'
url:              pochoi.github.io
baseurl:          /

author:
  name:           'Chi Po Choi'
  url:            pochoi.github.io

paginate:         5

# Custom vars
version:          2.1.0

email:              cpchoi (at) ucdavis (dot) edu
github_username:    pochoi
facebook_username:  balll

github:
  repo:           https://github.com/pochoi/

gems:             [jekyll-paginate, jekyll-gist]
